### ISSUE TITLE
HTTP Response Codes

### ISSUE THREAD

**Issue by GulKhan** [DocnetUK/php-japi#4]
I would like to be able to set my own HTTP Response codes, for example for Bad requests a 400 (invalid JSON or missing request params)

Perhaps allow an exception to be thrown and use the error code set in the exception object as the HTTP response code. 

For example:
throw new InvalidRequestException("missing params", 400);

At the moment this would give a response code of 500

**Comment by tomwalder** [comment]
I have a patch for this. I'll get it committed shortly

**Comment by tomwalder** [comment]
Should be fixed in the 2.0 branch. Feel free to re-open if needed.
